### ISSUE TITLE
Brazilian Portuguese localization

### ISSUE THREAD

**Issue by cyz** [education/codespaces-teaching-js-template#34]
Hi all 👋

We need create a Brazilian Portuguese translation and make sure it is working according to the English content.

Main folder: [https://github.com/education/codespaces-teaching-js-template](https://github.com/education/codespaces-teaching-js-template)

**Please compare each file below to its original in English and if required, please send a PR.**
| File | Status         |
|------|----------------|
| README.md     | pending review |

To send the localization, please, create the folder `translations/pt-BR`.

**Comment by WirelessLife** [comment]
The existing Brazilian Portuguese translation needs to be updated to include the new Copilot section added to the repo. We should also create Brazilian Portuguese translations of the videos as well.

**Comment by rogergcorrea27** [comment]
Hello, I can be the translator  En-US to PT-BR.

**Comment by rogergcorrea27** [comment]
Done, I just need of approval.

**Comment by cyz** [comment]
PR #39 approved, congratulations @rogergcorrea27 on your first GitHub contribution!

![image](https://github.com/education/codespaces-teaching-js-template/assets/2198735/be4e909e-247b-4887-be1c-5c5548c4aa4c)
